%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\smakrogiannis\Documents\MATLAB\MRIThighAnalysis\MetS_Experiments\CombinedResults_withNotes_EMGMM_GAC_8-12_Matching_MetS_BMI.xlsx
%    Worksheet: Data
%
% Auto-generated by MATLAB on 13-Mar-2020 11:36:00

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 54);

% Specify sheet and range
opts.Sheet = "Data";
opts.DataRange = "A4:BB308";

% Specify column names and types
opts.VariableNames = ["SubjectID", "VarName2", "VarName3", "VarName4", "VarName5", "Notes", "Firstusedslice", "Lastusedslice", "Leg", "AverageSATarea", "AverageMusclearea", "AverageIMFATarea", "AverageBonearea", "MuscleNSintensityave", "SATNSintensityave", "IMFATNSintensityave", "MuscleFSintensityave", "SATFSintensityave", "IMFATFSintensityave", "MuscleWSintensityave", "SATWSintensityave", "IMFATWSintensityave", "BoneNSintensityave", "BoneFSintensityave", "BoneWSintensityave", "VarName26", "TotalArea", "MTAT", "VarName29", "VarName30", "VarName31", "idno", "visit", "LATEST_DOV", "obesity", "Hyperglycemia", "Dyslipidemia_tgl", "Dyslipidemia_hdl", "Hypertension", "metS_score", "B_M_I", "weight", "height", "bmi", "WtKg", "HtCm", "waist_circ", "hip_circ", "WHR", "waistdep", "VarName51", "M_AvArheight2", "M_AvArweight", "M_AvArBMI"];
opts.VariableTypes = ["string", "double", "categorical", "double", "double", "string", "double", "double", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "string", "string", "string", "double", "double", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "string", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["SubjectID", "Notes", "VarName26", "VarName29", "VarName30", "VarName31", "VarName51"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["SubjectID", "VarName3", "Notes", "Leg", "VarName26", "VarName29", "VarName30", "VarName31", "VarName51"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "LATEST_DOV", "InputFormat", "");

% Import the data
DataMatrix = readtable("C:\Users\smakrogiannis\Documents\MATLAB\MRIThighAnalysis\MetS_Experiments\CombinedResults_withNotes_EMGMM_GAC_8-12_Matching_MetS_BMI.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts